# Change these first
owner: mailpace # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Application
    url: https://app.mailpace.com
  - name: Documentation
    url: https://docs.mailpace.com
  - name: Blog
    url: https://blog.mailpace.com
  - name: Landing Page
    url: https://mailpace.com
  - name: SMTP Server
    check: "tcp-ping"
    url: smtp.mailpace.com
    port: 25

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mailpace.com
  # baseUrl: /status
  logoUrl: https://mailpace.com/favicon.ico
  name: MailPace Status
  introTitle: Fast & Reliable Transactional Email Service

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
