# Change these first
owner: ohmysmtp # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Application
    url: https://app.ohmysmtp.com
  - name: Docs
    url: https://docs.ohmysmtp.com
  - name: Blog
    url: https://blog.ohmysmtp.com
  - name: Landing Page
    url: https://ohmysmtp.com
  #- name: SMTP
  #  url: smtp.ohmysmtp.com:25

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status2.ohmysmtp.com
  baseUrl: /status
  logoUrl: https://ohmysmtp.com/favicon.ico
  name: OhMySMTP Status Monitor
  introTitle: Fast & Reliable Transactional Email Delivery
  introMessage: Independent, privacy-focused and eco-friendly transactional emails 
  navbar:
    - title: OhMySMTP Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
